name: celestial
recipe: wordpress
config:
  webroot: wp
  php: '8.2'
  database: mysql:8.0
env_file:
  - .lando.env
services:
  myadmin:
    type: phpmyadmin
  appserver:
    overrides:
      volumes:
        - "./:/app/wp/wp-content/themes/celestial"
        - "/app/wp/wp-content/themes/celestial/wp"
tooling:
  acorn:
    service: appserver
    cmd: wp acorn --path=wp
