name: celestial
recipe: wordpress
config:
  webroot: ../lando/site
  php: '8.2'
  database: mysql:8.0
env_file:
  - .lando.env
excludes:
  - wordpress
services:
  myadmin:
    type: phpmyadmin
  appserver:
    overrides:
      volumes:
        - "./:/lando/site/wp-content/themes/celestial"
events:
  post-start:
    appserver: |
      cd /lando/site

      if [ ! -f "wp-settings.php" ]; then
        wp core download --version=${WORDPRESS_VERSION} --skip-content
        wp config create --dbname=wordpress --dbuser=wordpress --dbpass=wordpress --dbhost=database
      fi

      if ! wp core is-installed; then
        wp core install \
          --url=https://${PROJECT_NAME}.lndo.site/ \
          --title="${PROJECT_NAME}" \
          --admin_user=${ADMIN_USER} \
          --admin_password=${ADMIN_PASSWORD} \
          --admin_email=admin@${PROJECT_NAME}.lndo.site
        wp theme activate celestial
      fi
tooling:
  acorn:
    service: appserver
    cmd: wp --path=/lando/site acorn
proxy:
  myadmin:
    - "phpmyadmin.celestial.lndo.site"
