name: celestial
recipe: wordpress
config:
  webroot: wordpress
  php: '8.2'
  database: mysql:8.0
env_file:
  - .lando.env
services:
  myadmin:
    type: phpmyadmin
  appserver:
    overrides:
      volumes:
#        // TODO: Add each file and folder need for project
        - "./:/app/wordpress/wp-content/themes/celestial"
        - "/app/wordpress/wp-content/themes/celestial/wordpress/"
events:
  post-start:
    appserver: |
      cd wordpress

      if [ ! -f "wp-settings.php" ]; then
        wp core download --version=${WORDPRESS_VERSION} --skip-content
        wp config create --dbname=wordpress --dbuser=wordpress --dbpass=wordpress --dbhost=database

        wp core install \
          --url=https://${PROJECT_NAME}.lndo.site/ \
          --title="${PROJECT_NAME}" \
          --admin_user=${ADMIN_USER} \
          --admin_password=${ADMIN_PASSWORD} \
          --admin_email=admin@${PROJECT_NAME}.lndo.site
        wp theme activate celestial
      fi
tooling:
  acorn:
    service: appserver
    cmd: wp --path=/app/wordpress acorn
